apiVersion: v1
kind: Namespace
metadata:
  name: go-pgdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: go-pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12-alpine
          command: [ "docker-entrypoint.sh" ]
          args: [ "-c", "shared_preload_libraries=pg_stat_statements", "-c", "pg_stat_statements.track=all", "-c", "max_connections=200", "-c", "statement_timeout=120000" ]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: go-pgdb
            - name: POSTGRES_USER
              value: go-pgdb
            - name: POSTGRES_PASSWORD
              value: go-pgdb
            - name: TZ
              value: "Europe/Moscow"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: go-pgdb
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - nodePort: 30006
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres